# Generated by Django 4.1.7 on 2023-03-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Name',
            new_name='name',
        ),
    ]
