# Generated by Django 4.1.7 on 2023-03-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_name_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Desciption',
            new_name='Description',
        ),
    ]
