# Generated by Django 4.1.7 on 2023-03-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='name1',
        ),
    ]
