# Generated by Django 4.1.7 on 2023-03-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_rename_description_member_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='description1',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name1',
            new_name='name',
        ),
    ]
