# Generated by Django 4.1.7 on 2023-03-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_rename_description1_member_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='description',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='name1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AddField(
            model_name='member',
            name='image1',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
    ]
